### ISSUE TITLE
How to use sidebar big and mega menu

### ISSUE THREAD

**Issue by kurtwilbies** [ilhammeidi/enlite-starter#4]
How to use sidebar big and mega menu. Doesnt work. Can you send me code that indeed works.

**Comment by ilhammeidi** [comment]
sidebar big and mega menu only available for enlite prime https://themeforest.net/item/enlite-prime-reactjs-fullstack-website-template/23803960

**Comment by ilhammeidi** [comment]
> How to use sidebar big and mega menu. Doesnt work. Can you send me code that indeed works.

sidebar big and mega menu only available for enlite prime https://themeforest.net/item/enlite-prime-reactjs-fullstack-website-template/23803960

**Comment by kurtwilbies** [comment]
Dear Ilham,

Can you please donate me access to the source code. I have money to buy from themeforest.
